// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {snapshot} from '../models';
import {store} from '../models';

export function AddConnection(arg1:string,arg2:string):Promise<void>;

export function CreateBackup(arg1:string,arg2:string):Promise<string>;

export function CreateSnapshot(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DiffCollectionChanges(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number):Promise<main.DiffChangePage>;

export function DiffSnapshots(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.DiffSummaryResult>;

export function GCSnapshots(arg1:string,arg2:string,arg3:number):Promise<snapshot.GCResult>;

export function ListBackups():Promise<Array<store.Backup>>;

export function ListConnections():Promise<Array<main.ConnectionInfo>>;

export function ListSnapshots(arg1:string,arg2:string):Promise<Array<snapshot.Summary>>;

export function RemoveConnection(arg1:string):Promise<void>;

export function RestoreBackup(arg1:string,arg2:string):Promise<string>;

export function RestoreSnapshot(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TagSnapshot(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function TestConnection(arg1:string):Promise<Array<string>>;
