// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1, arg2) {
  return window['go']['main']['App']['AddConnection'](arg1, arg2);
}

export function CreateBackup(arg1, arg2) {
  return window['go']['main']['App']['CreateBackup'](arg1, arg2);
}

export function CreateSnapshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSnapshot'](arg1, arg2, arg3);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DiffCollectionChanges(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['DiffCollectionChanges'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function DiffSnapshots(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DiffSnapshots'](arg1, arg2, arg3, arg4);
}

export function GCSnapshots(arg1, arg2, arg3) {
  return window['go']['main']['App']['GCSnapshots'](arg1, arg2, arg3);
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListSnapshots(arg1, arg2) {
  return window['go']['main']['App']['ListSnapshots'](arg1, arg2);
}

export function RemoveConnection(arg1) {
  return window['go']['main']['App']['RemoveConnection'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function RestoreSnapshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreSnapshot'](arg1, arg2, arg3);
}

export function TagSnapshot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TagSnapshot'](arg1, arg2, arg3, arg4);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
