// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function AutoInstallAvailable() {
  return window['go']['main']['App']['AutoInstallAvailable']();
}

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function CheckOllama() {
  return window['go']['main']['App']['CheckOllama']();
}

export function ClassifySQL(arg1) {
  return window['go']['main']['App']['ClassifySQL'](arg1);
}

export function CompareVectors(arg1, arg2) {
  return window['go']['main']['App']['CompareVectors'](arg1, arg2);
}

export function CreateBackup(arg1, arg2) {
  return window['go']['main']['App']['CreateBackup'](arg1, arg2);
}

export function CreateCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2, arg3);
}

export function CreateIndex(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateIndex'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateSnapshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSnapshot'](arg1, arg2, arg3);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DeleteSavedQuery(arg1) {
  return window['go']['main']['App']['DeleteSavedQuery'](arg1);
}

export function DeleteWidget(arg1) {
  return window['go']['main']['App']['DeleteWidget'](arg1);
}

export function DeleteDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteDocument'](arg1, arg2, arg3, arg4);
}

export function DiffCollectionChanges(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['DiffCollectionChanges'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function DiffSchemas(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DiffSchemas'](arg1, arg2, arg3, arg4);
}

export function DiffSnapshots(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DiffSnapshots'](arg1, arg2, arg3, arg4);
}

export function DropCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['DropCollection'](arg1, arg2, arg3);
}

export function DropIndex(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DropIndex'](arg1, arg2, arg3, arg4);
}

export function EngineIDs() {
  return window['go']['main']['App']['EngineIDs']();
}

export function ExplainSQL(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExplainSQL'](arg1, arg2, arg3);
}

export function ExplainWithAI(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExplainWithAI'](arg1, arg2, arg3);
}

export function FixSQLError(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['FixSQLError'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GCSnapshots(arg1, arg2, arg3) {
  return window['go']['main']['App']['GCSnapshots'](arg1, arg2, arg3);
}

export function GenerateAPISchema(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateAPISchema'](arg1, arg2, arg3, arg4);
}

export function GenerateAggregation(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateAggregation'](arg1, arg2, arg3);
}

export function GenerateSchemaMigration(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateSchemaMigration'](arg1, arg2, arg3, arg4, arg5);
}

export function GenerateMockData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateMockData'](arg1, arg2, arg3, arg4, arg5);
}

export function GenerateSQL(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateSQL'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetTableSchema(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableSchema'](arg1, arg2, arg3);
}

export function InsertDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InsertDocument'](arg1, arg2, arg3, arg4);
}

export function InsertWebhookPayload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InsertWebhookPayload'](arg1, arg2, arg3, arg4);
}

export function InstallDependencies() {
  return window['go']['main']['App']['InstallDependencies']();
}

export function IsWebhookListenerRunning() {
  return window['go']['main']['App']['IsWebhookListenerRunning']();
}

export function InstallOllama() {
  return window['go']['main']['App']['InstallOllama']();
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ListCollections(arg1, arg2) {
  return window['go']['main']['App']['ListCollections'](arg1, arg2);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListIndexes(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListIndexes'](arg1, arg2, arg3);
}

export function ListOllamaModels(arg1) {
  return window['go']['main']['App']['ListOllamaModels'](arg1);
}

export function ListReferencingTables(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListReferencingTables'](arg1, arg2, arg3);
}

export function ListSavedQueries() {
  return window['go']['main']['App']['ListSavedQueries']();
}

export function ListWidgets() {
  return window['go']['main']['App']['ListWidgets']();
}

export function ListSnapshots(arg1, arg2) {
  return window['go']['main']['App']['ListSnapshots'](arg1, arg2);
}

export function ListTables(arg1, arg2) {
  return window['go']['main']['App']['ListTables'](arg1, arg2);
}

export function ManualInstallInstructions() {
  return window['go']['main']['App']['ManualInstallInstructions']();
}

export function PickMigrationsFolder() {
  return window['go']['main']['App']['PickMigrationsFolder']();
}

export function PickSQLiteFile() {
  return window['go']['main']['App']['PickSQLiteFile']();
}

export function PullOllamaModel(arg1, arg2) {
  return window['go']['main']['App']['PullOllamaModel'](arg1, arg2);
}

export function QueryDocuments(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['QueryDocuments'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function RemoveConnection(arg1) {
  return window['go']['main']['App']['RemoveConnection'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function RestoreSnapshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreSnapshot'](arg1, arg2, arg3);
}

export function RunAggregation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunAggregation'](arg1, arg2, arg3, arg4);
}

export function RunSavedQuery(arg1) {
  return window['go']['main']['App']['RunSavedQuery'](arg1);
}

export function RunSQLExecute(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunSQLExecute'](arg1, arg2, arg3, arg4);
}

export function RunSQLQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunSQLQuery'](arg1, arg2, arg3);
}

export function RunSQLQueryJob(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunSQLQueryJob'](arg1, arg2, arg3);
}

export function SaveAISettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAISettings'](arg1, arg2, arg3, arg4);
}

export function SecureCredentialStorageAvailable() {
  return window['go']['main']['App']['SecureCredentialStorageAvailable']();
}

export function SaveMigration(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveMigration'](arg1, arg2, arg3, arg4);
}

export function SaveQuery(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveQuery'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveWidget(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveWidget'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartWebhookListener(arg1) {
  return window['go']['main']['App']['StartWebhookListener'](arg1);
}

export function StopWebhookListener() {
  return window['go']['main']['App']['StopWebhookListener']();
}

export function SwitchTenant(arg1, arg2) {
  return window['go']['main']['App']['SwitchTenant'](arg1, arg2);
}

export function TagSnapshot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TagSnapshot'](arg1, arg2, arg3, arg4);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateDocument(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateDocument'](arg1, arg2, arg3, arg4, arg5);
}
