// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {depmanager} from '../models';
import {safeguard} from '../models';
import {snapshot} from '../models';
import {engine} from '../models';
import {store} from '../models';
import {ai} from '../models';
import {dashboard} from '../models';
import {schemadiff} from '../models';
import {migrations} from '../models';

export function AddConnection(arg1:main.ConnectionInput):Promise<void>;

export function AutoInstallAvailable():Promise<boolean>;

export function CancelJob(arg1:string):Promise<boolean>;

export function CheckDependencies():Promise<Array<main.DependencyStatus>>;

export function CheckOllama():Promise<depmanager.OllamaStatus>;

export function ClassifySQL(arg1:string):Promise<safeguard.Classification>;

export function CompareVectors(arg1:string,arg2:string):Promise<main.VectorComparison>;

export function CreateBackup(arg1:string,arg2:string):Promise<string>;

export function CreateCollection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateIndex(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function CreateSnapshot(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DeleteSavedQuery(arg1:string):Promise<void>;

export function DeleteWidget(arg1:string):Promise<void>;

export function DeleteDocument(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DiffCollectionChanges(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number):Promise<main.DiffChangePage>;

export function DiffSchemas(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<schemadiff.TableDiff>>;

export function DiffSnapshots(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.DiffSummaryResult>;

export function DropCollection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DropIndex(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EngineIDs():Promise<Array<string>>;

export function ExplainSQL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExplainWithAI(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FixSQLError(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<string>;

export function GCSnapshots(arg1:string,arg2:string,arg3:number):Promise<snapshot.GCResult>;

export function GenerateAPISchema(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GenerateAggregation(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateSchemaMigration(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<schemadiff.Migration>;

export function GenerateMockData(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function GenerateSQL(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string):Promise<string>;

export function GetAISettings():Promise<main.AISettingsInfo>;

export function GetTableSchema(arg1:string,arg2:string,arg3:string):Promise<engine.TableSchema>;

export function InsertDocument(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function InsertWebhookPayload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function InstallDependencies():Promise<string>;

export function InstallOllama():Promise<string>;

export function IsWebhookListenerRunning():Promise<boolean>;

export function ListBackups():Promise<Array<store.Backup>>;

export function ListCollections(arg1:string,arg2:string):Promise<Array<main.CollectionInfo>>;

export function ListConnections():Promise<Array<main.ConnectionInfo>>;

export function ListIndexes(arg1:string,arg2:string,arg3:string):Promise<Array<main.IndexInfo>>;

export function ListOllamaModels(arg1:string):Promise<Array<ai.OllamaModel>>;

export function ListReferencingTables(arg1:string,arg2:string,arg3:string):Promise<Array<main.IncomingForeignKey>>;

export function ListSavedQueries():Promise<Array<dashboard.SavedQuery>>;

export function ListWidgets():Promise<Array<dashboard.Widget>>;

export function ListSnapshots(arg1:string,arg2:string):Promise<Array<snapshot.Summary>>;

export function ListTables(arg1:string,arg2:string):Promise<Array<main.TableInfo>>;

export function ManualInstallInstructions():Promise<Array<string>>;

export function PickMigrationsFolder():Promise<string>;

export function PickSQLiteFile():Promise<string>;

export function PullOllamaModel(arg1:string,arg2:string):Promise<string>;

export function QueryDocuments(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number):Promise<main.QueryResult>;

export function RemoveConnection(arg1:string):Promise<void>;

export function RestoreBackup(arg1:string,arg2:string):Promise<string>;

export function RestoreSnapshot(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RunAggregation(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function RunSavedQuery(arg1:string):Promise<engine.SQLResult>;

export function RunSQLExecute(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function RunSQLQuery(arg1:string,arg2:string,arg3:string):Promise<engine.SQLResult>;

export function RunSQLQueryJob(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveAISettings(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SecureCredentialStorageAvailable():Promise<boolean>;

export function SaveMigration(arg1:string,arg2:string,arg3:string,arg4:string):Promise<migrations.SaveResult>;

export function SaveQuery(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function SaveWidget(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<string>;

export function StartWebhookListener(arg1:number):Promise<string>;

export function StopWebhookListener():Promise<void>;

export function SwitchTenant(arg1:string,arg2:string):Promise<void>;

export function TagSnapshot(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function TestConnection(arg1:string):Promise<Array<string>>;

export function UpdateDocument(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
